#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Game constants and configuration values - Roguelike Edition.
"""

# Screen settings (larger for roguelike experience)
WIDTH = 1280
HEIGHT = 720
FPS = 60
FULLSCREEN_WIDTH = 1920
FULLSCREEN_HEIGHT = 1080

# Colors
BLACK = (0, 0, 0)
WHITE = (255, 255, 255)
GREEN = (0, 255, 0)
RED = (255, 0, 0)
BLUE = (0, 0, 255)
YELLOW = (255, 255, 0)
GRAY = (128, 128, 128)
CYAN = (0, 255, 255)
MAGENTA = (255, 0, 255)
ORANGE = (255, 165, 0)
PURPLE = (128, 0, 128)
DARK_RED = (139, 0, 0)
DARK_GREEN = (0, 100, 0)
GOLD = (255, 215, 0)
SILVER = (192, 192, 192)

# Ship constants
SHIP_BASE_HEALTH = 6  # Hearts like in Isaac
SHIP_THRUST_POWER = 250
SHIP_MAX_SPEED = 350
SHIP_ROTATION_SPEED = 3.5
SHIP_FRICTION = 0.98
SHIP_INVULNERABILITY_TIME = 2.0
SHIP_BLINK_INTERVAL = 0.15
SHIP_BASE_DAMAGE = 1

# Bullet constants
BULLET_SPEED = 450
BULLET_LIFETIME = 2.5
SHOT_COOLDOWN = 250
RAPID_FIRE_COOLDOWN = 120

# Asteroid constants
ASTEROID_BASE_SIZE = 15
ASTEROID_MIN_SPAWN_DISTANCE = 150
ASTEROID_MIN_VERTICES = 6
ASTEROID_MAX_VERTICES = 10
ASTEROID_MIN_ROTATION_SPEED = -2.0
ASTEROID_MAX_ROTATION_SPEED = 2.0
ASTEROID_SIZE_LARGE = 3
ASTEROID_SIZE_MEDIUM = 2
ASTEROID_SIZE_SMALL = 1

# Difficulty multipliers
DIFFICULTY_EASY = 0
DIFFICULTY_NORMAL = 1
DIFFICULTY_HARD = 2

DIFFICULTY_SPEED_MULTIPLIER = {
    DIFFICULTY_EASY: 0.7,
    DIFFICULTY_NORMAL: 1.0,
    DIFFICULTY_HARD: 1.3
}

DIFFICULTY_ASTEROID_COUNT = {
    DIFFICULTY_EASY: 3,
    DIFFICULTY_NORMAL: 5,
    DIFFICULTY_HARD: 7
}

# Scoring
SCORE_ASTEROID_LARGE = 20
SCORE_ASTEROID_MEDIUM = 50
SCORE_ASTEROID_SMALL = 100
SCORE_MULTIPLIER_EASY = 1
SCORE_MULTIPLIER_NORMAL = 2
SCORE_MULTIPLIER_HARD = 3

# Currency system
COIN_VALUE_SMALL = 1
COIN_VALUE_MEDIUM = 5
COIN_VALUE_LARGE = 10
COIN_DROP_CHANCE = 0.3  # 30% chance per asteroid
COIN_LIFETIME = 10.0  # seconds

# Power-up constants
POWERUP_SPAWN_CHANCE = 0.12
POWERUP_LIFETIME = 12.0
POWERUP_DURATION = 10.0
POWERUP_SIZE = 12

# Power-up types
POWERUP_SHIELD = 'shield'
POWERUP_RAPID_FIRE = 'rapid_fire'
POWERUP_TRIPLE_SHOT = 'triple_shot'
POWERUP_EXTRA_LIFE = 'extra_life'
POWERUP_HEALTH = 'health'
POWERUP_SPEED = 'speed'
POWERUP_DAMAGE = 'damage'

POWERUP_COLORS = {
    POWERUP_SHIELD: CYAN,
    POWERUP_RAPID_FIRE: YELLOW,
    POWERUP_TRIPLE_SHOT: MAGENTA,
    POWERUP_EXTRA_LIFE: GREEN,
    POWERUP_HEALTH: RED,
    POWERUP_SPEED: ORANGE,
    POWERUP_DAMAGE: PURPLE
}

# Particle constants
PARTICLE_LIFETIME = 1.0
PARTICLE_MIN_SPEED = 20
PARTICLE_MAX_SPEED = 100
PARTICLE_COUNT_EXPLOSION = 15
PARTICLE_COUNT_THRUST = 3

# Room system (Isaac-like)
ROOM_WIDTH = WIDTH
ROOM_HEIGHT = HEIGHT - 100  # Leave space for HUD
ROOM_PADDING = 50
ROOM_TRANSITION_TIME = 0.5  # seconds

# Room types
ROOM_TYPE_NORMAL = 'normal'
ROOM_TYPE_BOSS = 'boss'
ROOM_TYPE_SHOP = 'shop'
ROOM_TYPE_TREASURE = 'treasure'
ROOM_TYPE_START = 'start'

# Room difficulty scaling
ROOM_DIFFICULTY_BASE = 1.0
ROOM_DIFFICULTY_PER_ROOM = 0.1
ROOM_MAX_DIFFICULTY = 3.0

# Level generation
LEVEL_MIN_ROOMS = 6
LEVEL_MAX_ROOMS = 12
LEVEL_BOSS_ROOMS = 1
LEVEL_SHOP_CHANCE = 0.3
LEVEL_TREASURE_CHANCE = 0.2

# Boss constants
BOSS_HEALTH_BASE = 50
BOSS_HEALTH_PER_LEVEL = 20
BOSS_SIZE_MULTIPLIER = 3.0
BOSS_DAMAGE = 2
BOSS_SPEED = 80

# Boss types
BOSS_ASTEROID_KING = 'asteroid_king'
BOSS_VOID_HUNTER = 'void_hunter'
BOSS_STAR_DESTROYER = 'star_destroyer'

# Boss attack patterns
BOSS_ATTACK_COOLDOWN = 3.0  # seconds
BOSS_PROJECTILE_COUNT = 8
BOSS_PROJECTILE_SPEED = 200

# Shop constants
SHOP_ITEM_COUNT = 4
SHOP_REROLL_COST = 5

# Shop item prices
SHOP_PRICE_HEALTH = 5
SHOP_PRICE_MAX_HEALTH = 15
SHOP_PRICE_DAMAGE = 10
SHOP_PRICE_FIRE_RATE = 10
SHOP_PRICE_SPEED = 8
SHOP_PRICE_SHIELD = 15
SHOP_PRICE_TRIPLE_SHOT = 20

# Permanent upgrades (meta-progression)
UPGRADE_MAX_HEALTH = 'max_health'
UPGRADE_BASE_DAMAGE = 'base_damage'
UPGRADE_FIRE_RATE = 'fire_rate'
UPGRADE_MOVE_SPEED = 'move_speed'
UPGRADE_STARTING_COINS = 'starting_coins'
UPGRADE_COIN_MULTIPLIER = 'coin_multiplier'

# Upgrade costs (in permanent currency)
UPGRADE_COSTS = {
    UPGRADE_MAX_HEALTH: [10, 20, 30, 50, 100],
    UPGRADE_BASE_DAMAGE: [15, 30, 50, 80, 120],
    UPGRADE_FIRE_RATE: [12, 25, 40, 60, 90],
    UPGRADE_MOVE_SPEED: [10, 20, 35, 55, 85],
    UPGRADE_STARTING_COINS: [8, 16, 24, 32, 40],
    UPGRADE_COIN_MULTIPLIER: [20, 40, 70, 110, 160]
}

# Upgrade max levels
UPGRADE_MAX_LEVEL = 5

# Save system
SAVE_FILE = 'savegame.json'
PROGRESS_FILE = 'progress.json'
ACHIEVEMENTS_FILE = 'achievements.json'
HIGHSCORE_FILE = 'highscore.json'
SETTINGS_FILE = 'settings.json'

# Achievement thresholds
ACHIEVEMENT_SCORE_100 = 100
ACHIEVEMENT_SCORE_500 = 500
ACHIEVEMENT_SCORE_1000 = 1000
ACHIEVEMENT_SCORE_5000 = 5000
ACHIEVEMENT_SCORE_10000 = 10000
ACHIEVEMENT_ASTEROIDS_10 = 10
ACHIEVEMENT_ASTEROIDS_50 = 50
ACHIEVEMENT_ASTEROIDS_100 = 100
ACHIEVEMENT_ASTEROIDS_500 = 500
ACHIEVEMENT_SURVIVE_60 = 60
ACHIEVEMENT_SURVIVE_300 = 300
ACHIEVEMENT_SURVIVE_600 = 600
ACHIEVEMENT_WAVE_5 = 5
ACHIEVEMENT_WAVE_10 = 10
ACHIEVEMENT_WAVE_20 = 20
ACHIEVEMENT_BOSSES_5 = 5
ACHIEVEMENT_ROOMS_20 = 20

# Game states
STATE_MENU = 0
STATE_SETTINGS = 1
STATE_PLAYING = 2
STATE_PAUSED = 3
STATE_GAME_OVER = 4
STATE_ACHIEVEMENTS = 5
STATE_HIGHSCORES = 6
STATE_ROOM_TRANSITION = 7
STATE_SHOP = 8
STATE_UPGRADES = 9
STATE_LEVEL_SELECT = 10

# Minimap constants
MINIMAP_SIZE = 150
MINIMAP_ROOM_SIZE = 20
MINIMAP_PADDING = 10
MINIMAP_X = WIDTH - MINIMAP_SIZE - 20
MINIMAP_Y = 20

# Door constants
DOOR_WIDTH = 60
DOOR_HEIGHT = 20
DOOR_OFFSET = 50

# Door positions
DOOR_TOP = 'top'
DOOR_BOTTOM = 'bottom'
DOOR_LEFT = 'left'
DOOR_RIGHT = 'right'

# Hearts/Health display
HEART_SIZE = 20
HEART_SPACING = 25
HEART_X_START = 10
HEART_Y = HEIGHT - 90
