#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Game constants and configuration values.
"""

# Screen settings
WIDTH = 800
HEIGHT = 600
FPS = 60

# Colors
BLACK = (0, 0, 0)
WHITE = (255, 255, 255)
GREEN = (0, 255, 0)
RED = (255, 0, 0)
BLUE = (0, 0, 255)
YELLOW = (255, 255, 0)
GRAY = (128, 128, 128)
CYAN = (0, 255, 255)
MAGENTA = (255, 0, 255)
ORANGE = (255, 165, 0)
PURPLE = (128, 0, 128)

# Ship constants
SHIP_THRUST_POWER = 200
SHIP_MAX_SPEED = 300
SHIP_ROTATION_SPEED = 3.0
SHIP_FRICTION = 0.98
SHIP_INVULNERABILITY_TIME = 3.0  # seconds after respawn
SHIP_BLINK_INTERVAL = 0.2  # blink interval when invulnerable

# Bullet constants
BULLET_SPEED = 400
BULLET_LIFETIME = 2.0  # seconds
SHOT_COOLDOWN = 200  # milliseconds
RAPID_FIRE_COOLDOWN = 100  # milliseconds with power-up

# Asteroid constants
ASTEROID_BASE_SIZE = 15
ASTEROID_MIN_SPAWN_DISTANCE = 150
ASTEROID_MIN_VERTICES = 6
ASTEROID_MAX_VERTICES = 10
ASTEROID_MIN_ROTATION_SPEED = -2.0
ASTEROID_MAX_ROTATION_SPEED = 2.0
ASTEROID_SIZE_LARGE = 3
ASTEROID_SIZE_MEDIUM = 2
ASTEROID_SIZE_SMALL = 1

# Difficulty multipliers
DIFFICULTY_EASY = 0
DIFFICULTY_NORMAL = 1
DIFFICULTY_HARD = 2

DIFFICULTY_SPEED_MULTIPLIER = {
    DIFFICULTY_EASY: 0.7,
    DIFFICULTY_NORMAL: 1.0,
    DIFFICULTY_HARD: 1.5
}

DIFFICULTY_ASTEROID_COUNT = {
    DIFFICULTY_EASY: 3,
    DIFFICULTY_NORMAL: 5,
    DIFFICULTY_HARD: 7
}

# Scoring
SCORE_ASTEROID_LARGE = 20
SCORE_ASTEROID_MEDIUM = 50
SCORE_ASTEROID_SMALL = 100
SCORE_MULTIPLIER_EASY = 1
SCORE_MULTIPLIER_NORMAL = 2
SCORE_MULTIPLIER_HARD = 3

# Power-up constants
POWERUP_SPAWN_CHANCE = 0.15  # 15% chance on asteroid destruction
POWERUP_LIFETIME = 10.0  # seconds
POWERUP_DURATION = 8.0  # seconds when active
POWERUP_SIZE = 10

# Power-up types
POWERUP_SHIELD = 'shield'
POWERUP_RAPID_FIRE = 'rapid_fire'
POWERUP_TRIPLE_SHOT = 'triple_shot'
POWERUP_EXTRA_LIFE = 'extra_life'

POWERUP_COLORS = {
    POWERUP_SHIELD: CYAN,
    POWERUP_RAPID_FIRE: YELLOW,
    POWERUP_TRIPLE_SHOT: MAGENTA,
    POWERUP_EXTRA_LIFE: GREEN
}

# Particle constants
PARTICLE_LIFETIME = 1.0  # seconds
PARTICLE_MIN_SPEED = 20
PARTICLE_MAX_SPEED = 100
PARTICLE_COUNT_EXPLOSION = 15
PARTICLE_COUNT_THRUST = 3

# Lives and respawn
MAX_LIVES = 3
RESPAWN_DELAY = 2.0  # seconds

# Wave progression
WAVE_ASTEROID_INCREMENT = 2  # Additional asteroids per wave
WAVE_SPEED_INCREMENT = 0.1  # Speed multiplier increment per wave

# Achievement thresholds
ACHIEVEMENT_SCORE_100 = 100
ACHIEVEMENT_SCORE_500 = 500
ACHIEVEMENT_SCORE_1000 = 1000
ACHIEVEMENT_SCORE_5000 = 5000
ACHIEVEMENT_ASTEROIDS_10 = 10
ACHIEVEMENT_ASTEROIDS_50 = 50
ACHIEVEMENT_ASTEROIDS_100 = 100
ACHIEVEMENT_SURVIVE_60 = 60  # seconds
ACHIEVEMENT_SURVIVE_300 = 300  # seconds
ACHIEVEMENT_WAVE_5 = 5
ACHIEVEMENT_WAVE_10 = 10

# File paths
SETTINGS_FILE = 'settings.json'
HIGHSCORE_FILE = 'highscore.json'
ACHIEVEMENTS_FILE = 'achievements.json'

# Game states
STATE_MENU = 0
STATE_SETTINGS = 1
STATE_PLAYING = 2
STATE_PAUSED = 3
STATE_GAME_OVER = 4
STATE_ACHIEVEMENTS = 5
STATE_HIGHSCORES = 6
